// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default (req, res) => {
  res.status(200).json([
    {
      countryId: "a00",
      countryName: "Egypt",
      picUrl:
        "https://as2.ftcdn.net/v2/jpg/01/63/78/09/1000_F_163780943_o2ld66b0CUfLhM9Cc40pe2G5BiU8xSyc.jpg",
      offers: [
        {
          placeId: "a00b00",
          placeName: "Numbia Aqua Beach Resort1",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b01",
          placeName: "Numbia Aqua Beach Resort2",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b02",
          placeName: "Numbia Aqua Beach Resort3",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b03",
          placeName: "Numbia Aqua Beach Resort4",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b04",
          placeName: "Numbia Aqua Beach Resort5",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b05",
          placeName: "Numbia Aqua Beach Resort6",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b06",
          placeName: "Numbia Aqua Beach Resort7",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b07",
          placeName: "Numbia Aqua Beach Resort8",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b08",
          placeName: "Numbia Aqua Beach Resort9",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a00b09",
          placeName: "Numbia Aqua Beach Resort10",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
      ],
    },
    {
      countryId: "a01",
      countryName: "Syria",
      picUrl:
        "https://as2.ftcdn.net/v2/jpg/01/63/78/09/1000_F_163780943_o2ld66b0CUfLhM9Cc40pe2G5BiU8xSyc.jpg",
      offers: [
        {
          placeId: "a01b00",
          placeName: "Numbia Aqua Beach Resort1",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b01",
          placeName: "Numbia Aqua Beach Resort2",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b02",
          placeName: "Numbia Aqua Beach Resort3",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b03",
          placeName: "Numbia Aqua Beach Resort4",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b04",
          placeName: "Numbia Aqua Beach Resort5",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b05",
          placeName: "Numbia Aqua Beach Resort6",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b06",
          placeName: "Numbia Aqua Beach Resort7",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b07",
          placeName: "Numbia Aqua Beach Resort8",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b08",
          placeName: "Numbia Aqua Beach Resort9",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a01b09",
          placeName: "Numbia Aqua Beach Resort10",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
      ],
    },
    {
      countryId: "a02",
      countryName: "Libia",
      picUrl:
        "https://as2.ftcdn.net/v2/jpg/01/63/78/09/1000_F_163780943_o2ld66b0CUfLhM9Cc40pe2G5BiU8xSyc.jpg",
      offers: [
        {
          placeId: "a02b00",
          placeName: "Numbia Aqua Beach Resort1",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b01",
          placeName: "Numbia Aqua Beach Resort2",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b02",
          placeName: "Numbia Aqua Beach Resort3",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b03",
          placeName: "Numbia Aqua Beach Resort4",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b04",
          placeName: "Numbia Aqua Beach Resort5",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b05",
          placeName: "Numbia Aqua Beach Resort6",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b06",
          placeName: "Numbia Aqua Beach Resort7",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b07",
          placeName: "Numbia Aqua Beach Resort8",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b08",
          placeName: "Numbia Aqua Beach Resort9",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
        {
          placeId: "a02b09",
          placeName: "Numbia Aqua Beach Resort10",
          rating: 5,
          date: "22.05.2023",
          oldPrice: 2999,
          currentPrice: 2399,
          currency: "pln",
          isLastminute: true,
          isAllInclusive: true,
        },
      ],
    },
  ]);
};
